print('Vvedite x pls')
x = int(input())
print('Vvedite y pls')
y = int(input())
print("x=", x, "y=", y)
print("Sum=", x + y)
print("Integer division =", x // y)
print("Modulus=", x % y)
print("Exponentiation=", x ** y)
