string = input('Please enter the string:\n')
print(string[2])
print(string[-2])
print(string[:5])
print(string[:-2])
print(string[2::2])
print(string[1::2])
print(string[::-1])
print(string[::-2])
print(len(string))
